config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root 'top_pages#top'
  get 'user_show_from_richmenu', to: 'top_pages#user_show_from_richmenu'
  get 'terms', to: 'top_pages#terms'
  get 'privacy_policy', to: 'top_pages#privacy_policy'
  get 'contact', to: 'top_pages#contact'
  get 'tutorial', to: 'top_pages#tutorial'
  get 'environment', to: 'top_pages#environment'
  get 'toothbrush/:toothbrush_id/dental_item/search', to: 'dental_items#search', as: 'dental_items_search'
  get 'toothbrush/search', to: 'toothbrushes#search'
  get 'user_sessions/login', to: 'user_sessions#login'
  get 'user_sessions/callback', to: 'user_sessions#callback'
  get 'guest_login', to: 'user_sessions#guest_login'
  delete 'logout', to: 'user_sessions#destroy'
  resources :toothbrushes do
    member do
      get 'update_state'
    end
    resources :dental_items, only: %i[new create update edit]
    get :index_search, on: :collection
  end
  resources :users, only: %i[edit update show]
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
end

app/controllers/top_pages_controller.rb
class TopPagesController < ApplicationController
  before_action :require_login, only: %i[user_show_from_richmenu]
  before_action :skip_login, only: %i[user_show_from_richmenu]
  def top
    @toothbrush = Toothbrush.all
  end

  def tutorial; end

  def user_show_from_richmenu; end

  def terms; end

  def privacy_policy; end

  def environment
    @cleanings = Toothbrush.cleaning.count
    @recyclings = Toothbrush.recycling.count
    @improvement = @cleanings + (@recyclings * 2)
  end
end

app/views/top_pages/environment.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-lg-6 col-md-5 text-center">
      <div><h1 class="mt-2 pt-5 pb-3">みんなで地球を綺麗にしましょう！</h1></div>
      <div class="text-center pt-5 pb-3">
        <p id="state-recycling"><%= "リサイクルされている歯ブラシ : #{@recyclings}本"%></p>
        <p id="state-cleaning"><%= "掃除中の歯ブラシ : #{@cleanings}本"%></p>
      </div>
      <div class="fw-bold improvement-count"><%= "現在の環境改善度 : #{@improvement}%"%></div>
      <div class="mt-5"><%= improvement_comment(@improvement)%></div>
      <div class="mt-5 pt-2 mb-3">
        <% if logged_in? %>
          <%= link_to 'マイ歯ブラシ', user_path(current_user) %>
        <% end %>
        <%= link_to '新しい歯ブラシで綺麗にする', toothbrush_search_path, class: "mx-3" %>
        <%= link_to "https://twitter.com/share?url=#{ "https://www.haburashi-life.com/" }&text=みんなで歯と地球を綺麗にしましょう！%0a%0a", 
                    class: 'ms-2', target: '_blank', rel: 'noopener'  do %>
          <i class="fa-brands fa-square-x-twitter fa-2x" style = "vertical-align: middle;"></i>
        <% end %>
      </div>
    </div>
    <div class="col-lg-6 col-md-7 environment-wrapper"></div>
  </div>
</div>

app/views/top_pages/privacy_policy.html.erb
<div class="container">
  <h1 class="title text-center pt-3">プライバシーポリシー</h1>
  <div class="row">
    <div>
      <h2>お客様から取得する情報</h2>
      <p>当社は、お客様から以下の情報を取得します。</p>
      <ul>
        <li>氏名(ニックネームやペンネームも含む)</li>
        <li>外部サービスでお客様が利用するID、その他外部サービスのプライバシー設定によりお客様が連携先に開示を認めた情報</li>
        <li>Cookie(クッキー)を用いて生成された識別情報</li>
      </ul>
    </div>

    <div>
      <h2>お客様の情報を利用する目的</h2>
      <ul>
        <li>当社は、お客様から取得した情報を、以下の目的のために利用します。</li>
        <li>当社サービスに関する登録の受付、お客様の本人確認、認証のため</li>
        <li>お客様の当社サービスの利用履歴を管理するため</li>
        <li>当社サービスにおけるお客様の行動履歴を分析し、当社サービスの維持改善に役立てるため</li>
        <li>当社のサービスに関するご案内をするため</li>
        <li>お客様からのお問い合わせに対応するため</li>
        <li>当社の規約や法令に違反する行為に対応するため</li>
        <li>当社サービスの変更、提供中止、終了、契約解除をご連絡するため</li>
        <li>当社規約の変更等を通知するため</li>
        <li>以上の他、当社サービスの提供、維持、保護及び改善のため</li>
      </ul>
    </div>
    <div>
      <h2>安全管理のために講じた措置</h2>
      <p>当社が、お客様から取得した情報に関して安全管理のために講じた措置につきましては、末尾記載のお問い合わせ先にご連絡をいただきましたら、法令の定めに従い個別にご回答させていただきます。</p>
    </div>

    <div>
      <h2>第三者提供</h2>
      <p>当社は、お客様から取得する情報のうち、個人データ（個人情報保護法第１６条第３項）に該当するものついては、あらかじめお客様の同意を得ずに、第三者（日本国外にある者を含みます。）に提供しません。</p>
      <p>但し、次の場合は除きます。</p>
      <ul>
        <li>個人データの取扱いを外部に委託する場合</li>
        <li>当社や当社サービスが買収された場合</li>
        <li>事業パートナーと共同利用する場合（具体的な共同利用がある場合は、その内容を別途公表します。）</li>
        <li>その他、法律によって合法的に第三者提供が許されている場合</li>
      </ul>
    </div>
    <div>
      <h2>アクセス解析ツール</h2>
      <p>当社は、お客様のアクセス解析のために、「Googleアナリティクス」を利用しています。Googleアナリティクスは、トラフィックデータの収集のためにCookieを使用しています。トラフィックデータは匿名で収集されており、個人を特定するものではありません。Cookieを無効にすれば、これらの情報の収集を拒否することができます。詳しくはお使いのブラウザの設定をご確認ください。Googleアナリティクスについて、詳しくは以下からご確認ください。</p>
      <p>https://marketingplatform.google.com/about/analytics/terms/jp/</p>
    </div>
      
    <div>
      <p>当社は、必要に応じて、このプライバシーポリシーの内容を変更します。この場合、変更後のプライバシーポリシーの施行時期と内容を適切な方法により周知または通知します。</p>
    </div>
    <div>
      <h2>お問い合わせ</h2>
      <p>お客様の情報の開示、情報の訂正、利用停止、削除をご希望の場合は、お問い合わせフォームにご連絡ください。</p>
      <p>
        <%= link_to "お問い合わせフォームはこちら", "https://docs.google.com/forms/d/e/1FAIpQLSdIrszOUpe3bT9QyJ-RsZDSV6evG_icrYJAs-1eKggamGoy8Q/viewform", class:"top-link"%>
      </p>
      <p>2024年01月16日 制定</p>
    </div>
  </div>
</div>

app/views/top_pages/terms.html.erb
<div class="container">
  <h1 class="title text-center pt-3">利用規約</h1>
  <div class="row">
    <div>
      <p>
        本規約は、当社が提供する「歯ブラシLife!」(以下「本サービス」といいます。)を利用される際に適用されます。ご利用にあたっては、本規約をお読みいただき、内容をご承諾の上でご利用ください。
      </p>
    </div>
    <div>
      <h2>第1条(規約の適用)</h2>
      <p>1 本規約は、当社が本サービスを提供する上で、利用者が本サービスの提供を受けるにあたっての諸条件を定めたものです。</p>
      <p>2 当社は、本サービスの提供に関して、本規約のほか、本サービスの利用に関する個別規約その他のガイドライン等を定めることがあります。この場合、当該個別規約その他のガイドライン等は、本規約の一部として利用者による本サービスの利用に優先して適用されるものとします。</p>
      <p>3 利用者が本サービスを利用された場合、利用者が本規約に同意したものとみなします。</p>
      <p>4 利用者が、未成年の場合、利用者は、本サービスの利用について、親権者等法定代理人の同意を得なければなりません。当社は、未成年者の利用者による本サービスの利用については、親権者等法定代理人の同意を得て行為されたものとみなします。</p>
    </div>

    <div>
      <h2>第2条(利用登録)</h2>
      <P>1 利用者は、当社が定める方法により必要事項を登録いただくことで、利用登録を行うことができます。</P>
      <P>2 利用者は、登録事項について、当社に対して正確かつ最新の情報を届け出なければなりません。</P>
      <P>3 登録内容が不正確若しくは虚偽であり、又は、変更内容について届出がされていないために、利用者が損害又は不利益を被ったとしても、当社は責任を負わないものとします。</P>
    </div>

    <div>
      <h2>第3条(IDの管理)</h2>
      <P>1 利用者が利用登録を行った場合、当社は利用者のIDを管理します。</P>
      <P>2 利用者は、ID及びパスワードを厳重に管理し、保管するものとし、これを第三者に貸与、譲渡、売買その他の方法をもって利用させてはならないものとします。ID又はパスワードの管理が不十分なことにより、利用者が損害又は不利益を被ったとしても、当社は責任を負わないものとします。</P>
      <P>3 当社は、利用者に発行したID及びパスワードによる本サービスの利用の一切につき、利用者による真正な利用か否かにかかわらず、利用者本人の行為とみなすものとし、利用者は当該行為の結果生じる一切の責任を負担するものとします。</P>
    </div>

    <div>
      <h2>第4条(知的財産権及びコンテンツ)</h2>
      <P>本サービスを構成する全ての素材に関する著作権を含む知的財産権その他の一切の権利は、当社又は当該権利を有する第三者に帰属しています。利用者は、本サービスの全ての素材に関して、一切の権利を取得することはないものとし、権利者の許可なく、素材に関する権利を侵害する一切の行為をしてはならないものとします。本規約に基づく本サービスの利用の許諾は、本サービスに関する当社又は当該権利を有する第三者の権利の使用許諾を意味するものではありません。</P>
    </div>

    <div>
      <h2>第5条(利用者による投稿)</h2>
      <P>1 本サービス内における利用者による書き込み、レビュー(以下「利用者投稿情報」といいます。)は、本サービスの不特定多数の利用者からアクセス及び閲覧されることを十分に理解の上、本サービスをご利用ください。利用者投稿情報については、これを行った利用者が一切の責任を負うものとします。</P>
      <ul>
        <li>真実ではないもの</li>
        <li>わいせつな表現又はヌード等のわいせつ画像を含むもの</li>
        <li>他人の名誉又は信用を傷つけるもの</li>
        <li>第三者のプライバシー権、肖像権、著作権その他の権利を侵害するもの</li>
        <li>コンピュータウィルスを含むもの</li>
        <li>当社の認めるウェブサイト以外のウェブサイトへのリンクやURL</li>
        <li>その他当社が不適当と判断するもの</li>
      </ul>
      <P>2 利用者は以下の情報の投稿を行うことはできません。</P>
      <p>3 利用者は、当社が利用者投稿情報を無償で使用することを許諾するものとします。許諾にあたり、利用者は以下を表明し保証するものとします。</p>
      <ul>
        <li>利用者投稿情報に関する著作権、著作隣接権、肖像権その他一切の権利について、正当な権利者であり、又は、正当な権利者から本サービスに係る利用者投稿情報の利用に必要な一切の許諾を受けていること。</li>
        <li>利用者投稿情報の投稿及び当社による利用が、第三者の著作権、著作隣接権、肖像権その他一切の権利を侵害しないこと。</li>
      </ul>
    </div>
    <div>
      <p>4 当社は、利用者に安全に本サービスを利用いただくことを目的として、利用者投稿情報の内容を監視することができるものとします。</p>
    </div>
    <div>
      <P>5 当社は、利用者投稿情報が本規約に違反する場合又は以下の事由に該当する場合、利用者への事前の通知なく利用者投稿情報を削除すること及び利用者の投稿の制限を行うことができるものとします。</P>
      <ul>
        <li>投稿から一定期間以上経過した場合</li>
        <li>本サービスの保守管理上、必要と認められる場合</li>
        <li>利用者投稿情報等の容量が当社の使用機器の所定容量を超過した場合又はその恐れが生じた場合</li>
      </ul>
    </div>
    <div>
      <P>6 当社は、前項による削除及び投稿の制限の理由につき、利用者に対し返答する義務を負うものではなく、削除及び制限につき、利用者に発生した損害又は不利益につき、責任を負いません。また、当社は、利用者投稿情報の削除義務を負うものではありません。</P>
    </div>
    <div>
      <P>7 利用者は、本条に係る利用者投稿情報の監視、削除及び投稿の制限について、あらかじめ同意するものとします。</P>
    </div>

    <div>
      <h2>第6条(利用者へのお知らせ)</h2>
      <p>当社は利用者に、当社が提供するサービスの最新情報やおすすめのお知らせのために定期的又は不定期にスマートフォン等のアプリのプッシュ通知を行います。</p>
    </div>

    <div>
      <h2>第7条(サービスの内容の変更、追加、停止)</h2>
      <P>当社は、利用者に事前の通知をすることなく、本サービスの内容の全部又は一部を変更、追加又は停止する場合があり、利用者はこれをあらかじめ承諾するものとします。</P>
    </div>

    <div>
      <h2>第8条(個人情報)</h2>
      <P>当社は、利用者による本サービスの利用によって取得する個人情報を、当社のプライバシーポリシーに従い、適切に取り扱います。</P>
    </div>

    <div>
      <h2>第9条(禁止事項)</h2>
      <P>1 利用者は、次の行為を行うことはできません。</P>
      <ul>
        <li>本サービスの運営を妨げ、又はそのおそれのある行為</li>
        <li>他の利用者による本サービスの利用を妨害する行為</li>
        <li>本サービスにかかる著作権その他の権利を侵害する行為</li>
        <li>当社、他の利用者又は第三者の権利又は利益(名誉権、プライバシー権及び著作権を含みますが、これらに限られません。)を侵害する行為</li>
        <li>公序良俗その他法令に違反する行為及びこれに違反する恐れのある行為</li>
        <li>本規約に違反する行為</li>
        <li>前各号の他、本サービスの趣旨に鑑みて当社が不適切と判断する行為</li>
      </ul>
      <p>2 利用者が前項に定める行為を行ったと当社が判断した場合、当社は、利用者に事前に通知することなく、本サービスの全部又は一部の利用停止その他当社が必要かつ適切と判断する措置を講じることができます。本項の措置により利用者に生じる損害又は不利益について、当社は、一切の責任を負わないものとします。</p>
    </div>
    
    <div>
      <h2>第10条(反社会的勢力の排除)</h2>
      <P>利用者は、当社に対し、次の事項を確約します。</P>
      <ul>
        <li>自らが、暴力団、暴力団関係企業、総会屋若しくはこれらに準ずる者又はその構成員(以下総称して「反社会的勢力」といいます。)ではないこと。</li>
        <li>自らの役員(業務を執行する社員、取締役、執行役又はこれらに準ずる者をいいます。)が反社会的勢力ではないこと。</li>
        <li>反社会的勢力に自己の名義を利用させ、本契約を締結するものでないこと。</li>
        <li>自ら又は第三者を利用して、次の行為をしないこと。</li>
          <h5>① 相手方に対する脅迫的な言動又は暴力を用いる行為</h5>
          <h5>② 法的な責任を超えた不当な要求行為</h5>
          <h5>③ 偽計又は威力を用いて相手方の業務を妨害し、又は信用を毀損する行為</h5>
      </ul>
    </div>

    <div>
      <h2>第11条(免責事項)</h2>
      <p>1 天災地変、戦争、テロ行為、暴動、労働争議、伝染病、法令の制定改廃、政府機関の介入その他不可抗力により、本サービスの全部又は一部の停止、中断、遅延が発生した場合、当社は、利用者に生じた損害又は不利益について一切責任を負いません。</p>
      <p>2 利用者は、通信回線やコンピュータの障害、システムメンテナンスその他の事由による本サービスの全部又は一部の停止、中断、遅延が起こり得ることを理解しているものとし、当社は、これらにより利用者に生じた損害又は不利益について一切責任を負いません。また、利用者の利用環境によって生じた損害又は不利益について、当社は一切責任を負いません。</p>
      <p>3 当社は、以下の掲げる事項について、明示的にも黙示的にも保証しません。</p>
      <ul>
        <li>本サービスの内容及び本サービスを通じて提供される情報の、有用性、完全性、正確性、最新性、信頼性、特定目的への適合性。</li>
        <li>本サービスで提供される情報が第三者の権利を侵害しないものであること。</li>
        <li>本サービスが将来にわたって存続し続けること。</li>
      </ul>
      <p>4 当社は、理由の如何を問わず、データ等の全部又は一部が滅失、毀損、又は改ざんされた場合に、これを復元する義務を負わないものとし、当該滅失、毀損、又は改ざんによりお客さま又は第三者に生じた損害等について一切の責任を負わないものとします。</p>
      <p>5 当社は、利用者による本サービスの利用に関連して、利用者に対して責任を負う場合には、該当の商品等の価額過去12ヶ月間に利用者が当社に支払った対価の金額10,000円を超えて賠償する責任を負わないものとし、また、付随的損害、間接損害、特別損害、将来の損害および逸失利益にかかる損害については、賠償する責任を負わないものとします。</p>
      <p>6 本条の他の条項にかかわらず、本サービスに関する当社と利用者との間の契約が消費者契約法に定める消費者契約となる場合であって、かつ、当社の故意又は重過失に起因するときは、免責規定は適用されません。</p>
    </div>

    <div>
      <h2>第12条(秘密保持)</h2>
      <P>利用者は、本サービスの利用にあたり、当社より開示を受け、又は知り得た一切の情報について、第三者に開示又は漏えいしてはならず、本サービスの利用以外の目的に使用してはなりません。</P>
    </div>

    <div>
      <h2>第13条(当社からの通知)</h2>
      <P>1 当社から利用者に対して通知を行う場合、利用者が登録したID宛にメッセージを送信する方法、本サービスに係るウェブサイト上への掲示その他当社が適当と判断する方法により行うものとします。</P>
      <P>2 当社が通知を行う場合において、前項のID宛に送信した場合、当該IDのルームに記録された時点で、当社の通知は利用者に到達したものとみなします。</P>
    </div>

    <div>
      <h2>第14条(第三者との紛争)</h2>
      <P>1 本サービスに関連して利用者と第三者間で発生した紛争については、利用者は自らの費用と責任で解決するものとし、当社は一切の責任を負わないものとします。</P>
      <P>2 前項に関し、当社が損害(弁護士費用を含みます。)を被った場合、利用者は当該損害を賠償するものとします。</P>
    </div>

    <div>
      <h2>第15条(権利義務の譲渡禁止)</h2>
      <P>利用者は、本規約に基づく契約上の地位及びこれにより生じる権利義務の全部または一部について、当社の書面による事前の承諾なく、第三者に対し、譲渡、移転、担保権の設定その他の処分をすることができません。</P>
    </div>

    <div>
      <h2>第16条(分離可能性)</h2>
      <P>本規約のいずれかの条項が利用者との本規約に基づく契約に適用される法令に違反し、無効とされる場合、当該条項は、その違反とされる限りにおいて、当該利用者との契約には適用されないものとします。この場合でも、本規約の他の条項の効力には影響しません。</P>
    </div>

    <div>
      <h2>第17条(本規約の変更)</h2>
      <P>当社は、本規約を変更する必要が生じた場合には、民法第548条の4(定型約款の変更)に基づき、本規約を変更することができます。本規約を変更する場合、当社は、その効力発生日を定め、効力発生日までに、電子メールの送信その他の方法により以下の事項を周知するものとします。</P>
      <ul>
        <li>本規約を変更する旨</li>
        <li>変更後の本規約の内容</li>
        <li>効力発生日</li>
      </ul>
    </div>

    <div>
      <h2>第18条(準拠法、裁判管轄)</h2>
      <P>1 本規約は、日本法に準拠して解釈されます。</P>
      <P>2 当社及び利用者は、本サービスに関し、当社と利用者との間で生じた紛争の解決について、利用者は商品等の引渡しを受けた日からXXを第一審の専属的合意管轄裁判所とすることにあらかじめ合意します。</P>
    </div>
  </div>
</div>

app/views/top_pages/top.html.erb
<% content_for :head do %>
  <meta name="turbo-visit-control" content="reload">
<% end %>
<div class="top-wrapper">
  <div class="container-fluid">
    <div class="row">
      <div class="col-12 col-sm-12 text-center pt-5">
        <h1 class="mt-3 pt-5" id="top-text">歯ブラシLife!</h1>
      </div>
      <div class="text-center pt-4 pb-2" id="catch-copy">
        <h3>みんなで歯も地球も綺麗にしましょう!</h4>
      </div>
      <div class="text-center pt-4">
        <% unless logged_in? %>
          <%= link_to "ゲストログイン", guest_login_path, class:"top-link me-4 pe-2 first-guest" %>
        <% end %>
          <%= link_to "環境改善度を確認する", environment_path, class:"top-link" %>
      </div>
    </div>
  </div>
</div>

<div class="top-contents">
  <div id="top_area"></div>
</div>

<div class="text-center py-4 top-contents">
  <% if logged_in?%>
    <%= link_to "ログアウト", logout_path, data: { 'turbo_method': :delete }, class:"btn my-2", id:"login-button" %>
  <% else %>
    <%= link_to "ゲストログイン", guest_login_path, class:"btn my-2 toothbrush-menu-button" %>
    <p>(LINE通知以外の機能をご利用できます)</p>
    <%= link_to "LINEでログイン", user_sessions_login_path, class: "btn my-2", id:"login-button" %>
  <% end %>
</div>