config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root 'top_pages#top'
  get 'user_show_from_richmenu', to: 'top_pages#user_show_from_richmenu'
  get 'terms', to: 'top_pages#terms'
  get 'privacy_policy', to: 'top_pages#privacy_policy'
  get 'contact', to: 'top_pages#contact'
  get 'tutorial', to: 'top_pages#tutorial'
  get 'environment', to: 'top_pages#environment'
  get 'toothbrush/:toothbrush_id/dental_item/search', to: 'dental_items#search', as: 'dental_items_search'
  get 'toothbrush/search', to: 'toothbrushes#search'
  get 'user_sessions/login', to: 'user_sessions#login'
  get 'user_sessions/callback', to: 'user_sessions#callback'
  get 'guest_login', to: 'user_sessions#guest_login'
  delete 'logout', to: 'user_sessions#destroy'
  resources :toothbrushes do
    member do
      get 'update_state'
    end
    resources :dental_items, only: %i[new create update edit]
    get :index_search, on: :collection
  end
  resources :users, only: %i[edit update show]
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
end

app/views/shared/_error_message.html.erb
<% if object.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="mt-auto">
  <div class="container-fluid" id="footer">
    <div class="container">
      <div class="row text-center pt-3">
        <div class="col-md-1"></div>
        <div class="col-md-2 py-2 col-6">
          <%= link_to "利用規約", terms_path, class:'footer-link' %>
        </div>
        <div class="col-lg-2 col-md-2 col-6 py-2">
          <%= link_to "プライバシーポリシー", privacy_policy_path, class:'footer-link' %>
        </div>
        <div class="col-lg-2 col-md-2 col-6 py-2">
          <%= link_to "お問い合わせ", "https://docs.google.com/forms/d/e/1FAIpQLSdIrszOUpe3bT9QyJ-RsZDSV6evG_icrYJAs-1eKggamGoy8Q/viewform", class:'footer-link' %>
        </div>
        <div class="col-md-2 col-6 py-2">
          <%= link_to "友だち追加", "https://lin.ee/2jlm07B", class:'footer-link', rel: 'noopener' %>
        </div>
        <div class="col-md-2 col-5 py-1">
          <%= link_to "https://twitter.com/share?url=#{ "https://www.haburashi-life.com" }&text=みんなで歯と地球を綺麗にしましょう！%0a%0a", 
                      class: 'footer-x-twitter', target: '_blank', rel: 'noopener'  do %>
            <i class="fa-brands fa-square-x-twitter fa-2x" style = "vertical-align: middle;"></i>
          <% end %>
        </div>
        <div class="col-md-1"></div>
      </div>
      <div class="row text-center mt-1">
        <div class="col"><p class='copy-right'>©2023 Haburashi-Life All Rights Reserved.</p></div>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header>
  <div class="container-fluid">
    <div class="container">
      <nav class="navbar navbar-expand-lg py-0">
        <%= link_to root_path, class: "navbar-brand" do %>
          <h1 class="text-dark fw-bold d-block app-title">歯ブラシLife!</h1>
        <% end %>
        <button type="button" class="navbar-toggler toothbrush-menu-button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
          <span>メニュー</span>
        </button>
        <div class="collapse navbar-collapse bg-transparent" id="navbarCollapse">
          <div class="navbar-nav ms-auto">
            <% if logged_in? %>
              <div class="nav-item dropdown">
                <button type="button" class="btn dropdown-toggle my-2 me-4 pe-2 toothbrush-menu-button" 
                        data-bs-toggle="dropdown">
                  歯ブラシ
                </button>
                <div class="dropdown-menu rounded col-4">
                  <%= link_to "他の人の歯ブラシ", toothbrushes_path, class: "dropdown-item" %>
                  <%= link_to "新しい歯ブラシ", toothbrush_search_path, class: "dropdown-item" %>
                  <%= link_to "環境改善度を確認", environment_path, class:"dropdown-item" %>
                </div>
              </div>
              <div class="nav-item dropdown">
                <button type="button" class="btn dropdown-toggle my-2 pe-3" 
                        data-bs-toggle="dropdown" id="user-menu-button">
                  ユーザー
                </button>
                <div class="dropdown-menu rounded col-4">
                  <%= link_to "マイページ", user_path(current_user), class: "dropdown-item" %>
                  <%= link_to 'ユーザー名編集',  edit_user_path(current_user), class: "dropdown-item" %>
                  <%= link_to 'ログアウト', logout_path, data: { 'turbo_method': :delete }, class: "dropdown-item" %>
                </div>
              </div>
            <% else %>
              <%= link_to "ログイン", user_sessions_login_path, 
                  class: "nav-item nav-link btn my-2 me-4 col-3 col-md-2 col-lg-4", id:"login-button" %>
              <%= link_to "みんなの歯ブラシ", toothbrushes_path, 
                  class: "nav-item nav-link btn my-2 col-5 col-sm-4 col-md-3 col-lg-8 toothbrush-menu-button" %>
            <% end %>
          </div>
        </div>
      </nav>
    </div>
  </div>
</header>

app/views/shared/_loading_animation.html.erb
<body id="animation-body">
  <div class="loader" id="loading_animation">
    <div><span class="animation"></span></div>
    <div><span class="animation"></span></div>
    <div><span class="animation"></span></div>
    <div><span class="animation"></span></div>
    <div><span class="animation"></span></div>
    <div><span class="animation"></span></div>
    <div><span class="animation"></span></div>
    <div><span class="animation"></span></div>
    <div><span class="animation"></span></div>
  </div>
  <div class="container" id="loading_text">
    <div class="row">
      <div class="loader-text col text-center">
        <h1>検索します！<br class="d-none d-lg-block"/>しばらくお待ちください・・・</h1>
      </div>
    </div>
  </div>
</body>

app/views/shared/_moving_text.html.erb
<div class='text-center moving-text pb-3'>
  <span>移</span>
  <span>動</span>
  <span>し</span>
  <span>ま</span>
  <span>す</span>
  <span>!</span>
  <span>し</span>
  <span>ば</span>
  <span>ら</span>
  <span>く</span>
  <span>お</span>
  <span>待</span>
  <span>ち</span>
  <span>く</span>
  <span>だ</span>
  <span>さ</span>
  <span>い</span>
  <span>・</span>
  <span>・</span>
  <span>・</span>
</div>

app/views/shared/_search_form.html.erb
<div class="col col-lg-6 mx-auto">
  <%= form_with url: url, method: :get, local: true do |f| %>
    <div class="input-group">
      <%= f.search_field :keyword, value: params[:keyword], class: "form-control mb-3 mt-2", id: "text-form" %>
      <%= f.submit '検索', class: "btn btn-success mb-3 mt-2", id: "search-start" %>
    </div>
  <% end %>
</div>
<div class="row justify-content-center">
  <div class="col"></div>
  <div class="col-lg-3 col-md-4 col-sm-5">
    <div class="dropdown">
      <button class="btn dropdown-toggle me-lg-5 search-guide-button mb-3" type="button" data-bs-toggle="dropdown" aria-expanded="false" id="toothbrush-button">
        主要なメーカーで検索
      </button>
      <ul class="dropdown-menu">
        <li><a class="dropdown-item" id="search-guide">メーカー名をクリックすると、検索フォームに入力されます!</a></li>
        <li><a class="dropdown-item" id="dropdown-text">LION</a></li>
        <li><a class="dropdown-item" id="dropdown-text">花王</a></li>
        <li><a class="dropdown-item" id="dropdown-text">サンスター</a></li>
        <li><a class="dropdown-item" id="dropdown-text">エビス</a></li>
        <li><a class="dropdown-item" id="dropdown-text">アイオニック</a></li>
      </ul>
    </div>
  </div>
  <div class="col-lg-3 col-md-4 col-sm-5">
    <div class="dropdown">
      <button class="btn dropdown-toggle search-guide-button mb-3" type="button" data-bs-toggle="dropdown" aria-expanded="false" id="toothbrush-button">
        主要なブランドで検索
      </button>
      <ul class="dropdown-menu">
        <li><a class="dropdown-item" id="search-guide">ブランド名をクリックすると、検索フォームに入力されます!</a></li>
        <li><a class="dropdown-item" id="dropdown-text">GUM</a></li>
        <li><a class="dropdown-item" id="dropdown-text">NONIO</a></li>
        <li><a class="dropdown-item" id="dropdown-text">シュミテクト</a></li>
        <li><a class="dropdown-item" id="dropdown-text">クリニカ</a></li>
        <li><a class="dropdown-item" id="dropdown-text">ピュオーラ</a></li>
      </ul>
    </div>
  </div>
  <div class="col"></div>
</div>