config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root 'top_pages#top'
  get 'user_show_from_richmenu', to: 'top_pages#user_show_from_richmenu'
  get 'terms', to: 'top_pages#terms'
  get 'privacy_policy', to: 'top_pages#privacy_policy'
  get 'contact', to: 'top_pages#contact'
  get 'tutorial', to: 'top_pages#tutorial'
  get 'environment', to: 'top_pages#environment'
  get 'toothbrush/:toothbrush_id/dental_item/search', to: 'dental_items#search', as: 'dental_items_search'
  get 'toothbrush/search', to: 'toothbrushes#search'
  get 'user_sessions/login', to: 'user_sessions#login'
  get 'user_sessions/callback', to: 'user_sessions#callback'
  get 'guest_login', to: 'user_sessions#guest_login'
  delete 'logout', to: 'user_sessions#destroy'
  resources :toothbrushes do
    member do
      get 'update_state'
    end
    resources :dental_items, only: %i[new create update edit]
    get :index_search, on: :collection
  end
  resources :users, only: %i[edit update show]
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
end

app/models/dental_item.rb
class DentalItem < ApplicationRecord
  belongs_to :user
  belongs_to :toothbrush

  validates :toothbrush_id, presence: true
  validates :user_id, presence: true

  validate :validate_dental_items_count, on: :create

  private

  def validate_dental_items_count
    if user&.dental_items&.where(toothbrush_id:)&.count.to_i >= 5
      errors.add(:base, '5つまでしか登録できません')
    end
  end
end

app/controllers/dental_items_controller.rb
class DentalItemsController < ApplicationController
  include RakutenSearch
  before_action :set_toothbrush, only: %i[new create]

  def search; end

  def new
    if params[:keyword].blank?
      redirect_to dental_items_search_path, warning: '検索ワードを入力してください'
    else
      @results = search_results
      @results = paginate_results
    end
  end

  def create
    @dental_item = current_user.dental_items.new(rakuten_params.merge(toothbrush_id: @toothbrush.id))
    if current_user.registered?(@dental_item)
      redirect_to new_toothbrush_dental_item_path, status: :unprocessable_entity, danger: 'すでに登録されています'
    elsif @dental_item.save
      redirect_to toothbrush_path(@dental_item.toothbrush_id), success: 'デンタルグッズの登録が行われました！'
    else
      redirect_to new_toothbrush_dental_item_path, status: :unprocessable_entity, danger: '歯ブラシに登録出来るデンタルグッズは5つまでです'
    end
  end

  private

  def rakuten_params
    { item_code: params[:code], item_name: params[:name], item_url: params[:url],
      item_image_urls: params[:image], item_genre_id: params[:genre_id] }
  end

  def set_toothbrush
    @toothbrush = Toothbrush.find(params[:toothbrush_id])
  end
end

app/views/dental_items/_search_guide.html.erb
<div class="text-center mt-3">
  <h2>検索できるデンタルグッズ</h2>
</div>
<div class="row justify-content-center align-items-start">
  <div class="col-4 col-lg-3">
    <%= image_tag "dental_floss.png", class:"img-fluid mx-auto my-2" %>
  </div>
  <div class="col-4 col-lg-3">
    <%= image_tag "one_tuft_brush.png", class:"img-fluid mx-auto my-2" %>
  </div>
  <div class="col-4 col-lg-3">
    <%= image_tag "interdental_brush.png", class:"img-fluid mx-auto my-2" %>
  </div>
  <div class="col col-lg-3">
    <%= image_tag "dental_paste.png", class:"img-fluid mx-auto my-2" %>
  </div>
  <div class="col col-lg-3">
    <%= image_tag "dental_items_guide.png", class:"img-fluid mx-auto my-2" %>
  </div>
</div>

app/views/dental_items/_search_result.html.erb
<div class="card mb-1">
  <div class="row">
    <div class="col-4">
      <%= image_tag(result['mediumImageUrls'][0], size: '128x128') if result['mediumImageUrls'].present? %>
    </div>
    <div class="col-8">
      <div class="card-body">
        <p class="card-title" title="<%= result.name %>">
          <%= truncate(result.name, length: 40) %>
        </p>
          <%= link_to 'このグッズを追加！', toothbrush_dental_items_path(toothbrush_id: @toothbrush.id,
                                                        code: result['itemCode'],
                                                        name: result['itemName'],
                                                        genre_id: result['genreId'],
                                                        url: result['itemUrl'],
                                                        image: result['mediumImageUrls'][0]),
                                                        class: 'btn',
                                                        id: 'toothbrush-button',
                                                        data: { 'turbo_method': :post } %>
      </div>
    </div>
  </div>
</div>

app/views/dental_items/new.html.erb
<div class="container-fluid" id="search-form">
  <div class="row py-3">
    <div class="col-lg-10 offset-lg-1 text-center">
      <h1 >検索結果</h1>
    </div>
  </div>
  <% if @results.present? %>
    <div class="row">
      <% @results.each do |result| %>
        <div class="col-sm-12 col-md-4 col-lg-3 pb-2">
          <%= render "dental_items/search_result", result: result %>
        </div>
      <% end %>
    </div>
  <% else %>
    <p class="text-center">ごめんなさい！このキーワードを持つデンタルグッズは、楽天市場には無いみたいです・・・</p>     
    <p class="text-center">検索ワードを変えてもう一度検索してみてください。</p> 
    <%= render 'shared/search_form', url: new_toothbrush_dental_item_path %>
    <%= render 'search_guide' %>
  <% end %>
  <%= render 'shared/moving_text' %>
  <%= paginate @results, pagination_class: "flex-wrap justify-content-center", theme: 'bootstrap-5'%>
</div>

<body id="animation-body">
  <%= render 'shared/loading_animation' %>
</body>

app/views/dental_items/search.html.erb
<div class="container" id="search-form">
  <div class='text-center'>
    <h1 class="mt-5">歯ブラシと一緒に使うデンタルグッズを登録しましょう!</h1>
    <h1>(5つまで登録出来ます)</h1>
  </div>
  <%= render 'shared/search_form', url: new_toothbrush_dental_item_path %>
  <%= render 'search_guide' %>
</div>

<body id="animation-body">
  <%= render 'shared/loading_animation' %>
</body>