config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root 'top_pages#top'
  get 'user_show_from_richmenu', to: 'top_pages#user_show_from_richmenu'
  get 'terms', to: 'top_pages#terms'
  get 'privacy_policy', to: 'top_pages#privacy_policy'
  get 'contact', to: 'top_pages#contact'
  get 'tutorial', to: 'top_pages#tutorial'
  get 'environment', to: 'top_pages#environment'
  get 'toothbrush/:toothbrush_id/dental_item/search', to: 'dental_items#search', as: 'dental_items_search'
  get 'toothbrush/search', to: 'toothbrushes#search'
  get 'user_sessions/login', to: 'user_sessions#login'
  get 'user_sessions/callback', to: 'user_sessions#callback'
  get 'guest_login', to: 'user_sessions#guest_login'
  delete 'logout', to: 'user_sessions#destroy'
  resources :toothbrushes do
    member do
      get 'update_state'
    end
    resources :dental_items, only: %i[new create update edit]
    get :index_search, on: :collection
  end
  resources :users, only: %i[edit update show]
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
end

app/models/toothbrush.rb
class Toothbrush < ApplicationRecord
  belongs_to :user
  has_many :dental_items, dependent: :destroy

  validates :user_id, presence: true
  validates :comment, length: { maximum: 100 }

  enum state: { not_started: 0, using: 1, end_used: 2, cleaning: 3, recycling: 4 }
  enum brush_material: { nylon_hair: 0, animal_hair: 1, electric: 2, other: 3 }
  enum hardness: { normal: 0, soft: 1, hard: 2 }

  def self.ransackable_attributes(_auth_object = nil)
    %w[item_name]
  end

  scope :end_toothbrushed, -> { using.where('end_use_at <= ?', Time.current).where.not(brush_material: :electric) }
  scope :using_electric, -> { using.electric.where('end_use_at <= ?', Time.current) }
  scope :used, -> { where.not(state: :not_started) }
  scope :using_threedays, -> { used.where('created_at <= ?', Time.current - 3.days) }
end

app/controllers/toothbrushes_controller.rb
class ToothbrushesController < ApplicationController
  include RakutenSearch #controllers/concerns/rakuten_search.rb
  include ToothbrushesHelper
  require 'line_message'
  before_action :require_login, only: %i[edit new search]
  before_action :set_toothbrush, only: %i[show edit update update_state]

  def index # rubocop:disable Metrics/AbcSize
    @q = Toothbrush.ransack(params[:q])# params[:q]でユーザーが入力した検索ワードを受け取り、その検索ワードに該当するデータをインスタンス変数に格納させる。検索ワードに該当するToothbrushのデータをインスタンス変数に代入する、という処理か？
    @toothbrushes = if logged_in?
                      @q.result(distinct: true).includes(:user)
                        .where.not(user: current_user).order(created_at: :desc).page(params[:page]).per(12)
                    else
                      @q.result(distinct: true).includes(:user).order(created_at: :desc).page(params[:page]).per(12)
                    end
  end

  def show
    @dental_items = @toothbrush.dental_items.to_a
  end

  def edit; end

  def search; end

  def new
    if params[:keyword].blank?
      redirect_to toothbrush_search_path, warning: '検索ワードを入力してください'
    else
      @results = search_results
      @results = paginate_results
    end
  end

  def create
    @toothbrush = current_user.toothbrushes.new(rakuten_params)
    @toothbrush.save
    redirect_to edit_toothbrush_path(@toothbrush), success: '歯ブラシが選択されました！続けてブラシの素材、やわらかさ、使い終わる日を決めましょう！'
  end

  def update
    check_blank
    @toothbrush.update(toothbrush_params)
    change_state
    redirect_to toothbrush_path(@toothbrush), success: '内容が登録されました！'
  end

  def destroy
    @toothbrush = current_user.toothbrushes.find(params[:id])
    @toothbrush.destroy!
    redirect_to user_path(current_user), success: '歯ブラシを削除しました'
  end

  def update_state
    new_state = params[:new_state]
    if @toothbrush.end_used? && new_state.in?(%w[cleaning recycling]) || @toothbrush.cleaning? && new_state.in?(%w[recycling])
      @toothbrush.update(state: new_state)
      redirect_to environment_path, success: 'また少し、環境が整いました!ご協力ありがとうございます!'
    elsif new_state.in?(%w[end_used])
      @toothbrush.end_use_at = Time.current
      @toothbrush.update(state: new_state)
      push_end_used_message
      redirect_to toothbrush_path(@toothbrush), success: '歯ブラシを使い終わりました!'
    end
  end

  def index_search
    @toothbrush = if logged_in?
                    Toothbrush.where('item_name like ?', "%#{params[:q]}%").where.not(user_id: current_user.id)
                  else
                    Toothbrush.where('item_name like ?', "%#{params[:q]}%")
                  end
    respond_to(&:js)
  end

  private

  def set_toothbrush
    @toothbrush = Toothbrush.find(params[:id])
  end

  def rakuten_params
    { item_code: params[:code], item_name: params[:name], item_url: params[:url], item_image_urls: params[:image] }
  end

  def toothbrush_params
    params.require(:toothbrush).permit(:end_use_at, :brush_material, :hardness, :state, :comment)
  end

  def change_state
    if @toothbrush.end_use_at < Time.current && @toothbrush.using? || @toothbrush.end_use_at < Time.current && @toothbrush.not_started?
      @toothbrush.update(state: 2)
    elsif @toothbrush.not_started?
      @toothbrush.update(state: 1)
      push_start_message
    end
  end

  def check_blank
    params[:toothbrush][:comment] = '' if params[:toothbrush][:comment].blank?
  end

  def push_start_message
    line_user_id = current_user.line_user_id
    alt_text = "新しい歯ブラシの使用を開始しました！"
    header_text = "新しい歯ブラシの使用開始です!"
    hero_image = @toothbrush.item_image_urls.to_s
    item_name = @toothbrush.item_name.to_s
    contents_text = "歯ブラシの使用終了日を決めると、終了日が来た際にお知らせいたします!"
    label_text = "歯ブラシの設定を確認する"
    link_uri = "https://www.haburashi-life.com#{edit_toothbrush_path(@toothbrush)}"
    LineMessage.send_message_to_user(line_user_id, alt_text, header_text, hero_image, item_name,
                                     contents_text, label_text, link_uri)
  end

  def push_end_used_message
    line_user_id = current_user.line_user_id
    alt_text = "歯ブラシを使い終わりました"
    header_text = "次の歯ブラシを使い終わりました"
    hero_image = @toothbrush.item_image_urls.to_s
    item_name = @toothbrush.item_name.to_s
    link_uri = "https://www.haburashi-life.com#{@toothbrush.id}"
    if @toothbrush.electric?
      contents_text = "電動歯ブラシの処理は、各自治体の決まりに従いましょう!"
      label_text = "歯ブラシの詳細を確認する"
    else
      contents_text = "掃除道具として使うのか、それともリサイクルするのか、決めましょう！"
      label_text = "使い終わった後を決める"
    end
    LineMessage.send_message_to_user(line_user_id, alt_text, header_text, hero_image, item_name,
                                     contents_text, label_text, link_uri)
  end
end

app/helpers/toothbrushes_helper.rb
module ToothbrushesHelper
  def end_use_at_text(toothbrush)
    if toothbrush.not_started?
      '使用終了日(目安として一ヶ月後の日付を表示しています)'
    elsif toothbrush.electric? && toothbrush.using?
      '次のブラシの交換予定日'
    elsif toothbrush.using?
      '現在の使用終了日'
    else
      '使用終了日'
    end
  end

  def brush_material_text
    Toothbrush.brush_materials_i18n.invert.map { |key, value| [key, value] }
  end

  def hardness_text
    Toothbrush.hardnesses_i18n.invert.map { |key, value| [key, value] }
  end

  def display_end_use_at(toothbrush)
    if toothbrush.end_use_at
      toothbrush.end_use_at.strftime('%Y-%m-%d')
    else
      toothbrush.created_at.since(1.month).strftime('%Y-%m-%d')
    end
  end

  def using_3days(toothbrush)
    (Time.current - 3.days > toothbrush.created_at && toothbrush.state != toothbrush.not_started?) ||
      (toothbrush.end_used? || toothbrush.cleaning? || toothbrush.recycling?)
  end

  def not_end_used_only(toothbrush)
    if toothbrush.not_started? || toothbrush.using?
      false
    else
      true
    end
  end

  def border_color(toothbrush)
    if toothbrush.recycling?
      "recycling-border"
    elsif toothbrush.cleaning?
      "cleaning-border"
    elsif toothbrush.using?
      "using-border"
    elsif toothbrush.end_used?
      "end_used-border"
    end
  end

  def improvement_comment(improvement) # rubocop:disable Metrics/CyclomaticComplexity,Metrics/MethodLength,Metrics/PerceivedComplexity
    if improvement < 30
      'まだまだ改善が必要ですね・・・みんなで力を合わせて綺麗にしましょう!'
    elsif improvement >= 30 && improvement < 50
      '少し綺麗になってきましたね。でも、もっと綺麗にできそうですね?'
    elsif improvement >= 50 && improvement < 70
      'どんどん綺麗になってきています!この調子で綺麗にしていきましょう!'
    elsif improvement >= 70 && improvement < 100
      'かなり綺麗になりました!あと一息、みんなで力を合わせましょう!'
    elsif improvement <= 100
      'みなさんのおかげで環境が整いました!おめでとうございます!'
    end
  end
end

app/views/toothbrushes/_dental_item.html.erb
<div class="col-sm-12 col-lg-4 mb-3">
  <div id="dental-item">
    <div class="card">
      <%= image_tag dental_item.item_image_urls, size: '128x128' if dental_item.item_image_urls.present? %>
      <div class="card-body" id="dental-item-card">
        <p class="card-title">
          <%= dental_item.item_name %>
        </p>
      </div>
    </div>
  </div>
</div>

app/views/toothbrushes/_index_search.html.erb
<%= search_form_for @q, url: url do |f| %>
  <div data-controller="autocomplete" data-autocomplete-url-value="/toothbrushes/index_search" role="combobox">
    <div class="input-group mb-3">
      <%= f.search_field :item_name_cont, class: 'form-control', 
                          placeholder: "使われている歯ブラシから探す", data: { autocomplete_target: 'input' } %>
      <%= f.submit class: 'btn btn-primary justify-content-center' %>
      <%= f.hidden_field :item_name, data: { autocomplete_target: 'hidden' } %>
      <ul class="list-group" data-autocomplete-target="results">
      </ul>
    </div>
  </div>
<% end %>

app/views/toothbrushes/_search_form.html.erb
<%= search_form_for @q, url: url do |f| %>
  <div data-controller="autocomplete" data-autocomplete-url-value="/toothbrushes/index_search" role="combobox">
    <div class="input-group mb-3">
      <%= f.search_field :item_name_cont, class: 'form-control', 
                          placeholder: "使われている歯ブラシから探す", data: { autocomplete_target: 'input' } %>
      <%= f.submit class: 'btn btn-primary justify-content-center' %>
      <%= f.hidden_field :item_name, data: { autocomplete_target: 'hidden' } %>
      <ul class="list-group" data-autocomplete-target="results">
      </ul>
    </div>
  </div>
<% end %>

app/views/toothbrushes/_search_guide.html.erb
<div class="text-center mt-3">
  <h2>検索できる歯ブラシ</h2>
</div>
<div class="row justify-content-evenly align-items-start">
  <div class="col-6 col-lg-3">
    <%= image_tag "electric_brush.png", class:"img-fluid mb-1 mt-3" %>
  </div>
  <div class="col-6 col-lg-3">
    <%= image_tag "normal_brush.png", class:"img-fluid mb-1 mt-3" %>
  </div>
  <div class="col-6 col-lg-3">
    <%= image_tag "all_brush.png", class:"img-fluid mb-1 mt-3" %>
  </div>
  <div class="col-6 col-lg-3">
    <%= image_tag "toothbrush_guide.png", class:"img-fluid mb-1 mt-3" %>
  </div>
</div>

app/views/toothbrushes/_search_result.html.erb
<div class="card mb-1">
  <div class="row">
    <div class="col-5">
      <%= image_tag(result['mediumImageUrls'][0], size: '128x128') if result['mediumImageUrls'].present? %>
    </div>
    <div class="col-7">
      <div class="card-body">
        <p class="card-title" title="<%= result.name %>">
          <%= truncate(result.name, length: 40) %>
        </p>
          <%= link_to 'この歯ブラシを使う！', toothbrushes_path(code: result['itemCode'],
                                                        name: result['itemName'],
                                                        url: result['itemUrl'],
                                                        image: result['mediumImageUrls'][0]),
                                                        class: 'btn',
                                                        id: 'toothbrush-button',
                                                        data: { 'turbo_method': :post } %>
      </div>
    </div>
  </div>
</div>

app/views/toothbrushes/_toothbrush.html.erb
<div class="col-12 col-sm-6 col-lg-3 mb-3">
  <div id="toothbrushes-index">
    <div class="card rounded-0 border-2" id="<%= border_color(toothbrush) %>">
      <div class="text-center">
        <%= image_tag toothbrush.item_image_urls, size: '128x128' if toothbrush.item_image_urls.present? %>
      </div>
      <div class="card-body" id="card-font">
        <p class="card-title text-center" title="<%= toothbrush.item_name %>">
          <%= truncate(toothbrush.item_name, length: 25) %>
        </p>
        <ul class="list-group">
          <%  if toothbrush.comment.present? %>
            <li class="list-group-item text-center rounded-0 border-start-0  border-end-0">
              <%= truncate(toothbrush.comment, length: 25) %>
            </li>
          <% end %>
          <li class="list-group-item text-center rounded-0 border-start-0  border-end-0 border-bottom-0">
            <%= link_to '詳細', toothbrush_path(toothbrush), class:"btn btn-dark rounded-pill", id:"toothbrush-button" %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/toothbrushes/index.html.erb
<div class="container-fluid pt-3" id="index-container">
  <div class="row">
    <div class="col-lg-10 offset-lg-1 text-center mb-2">
      <h4>歯ブラシ一覧</h4>
    </div>
  </div>
  
  <div class="row mb-3">
    <div class="col-8 col-md-7 col-lg-4 mx-auto">
      <%= render 'index_search', url: toothbrushes_path %>
    </div>
  </div>

  <div class="col-12">
    <div class="row">
      <% if @toothbrushes.present? %>
        <%= render @toothbrushes %>
      <% else %>
        <div class="row mt-5">
          <p class="text-center">使用されている歯ブラシはありません</p>
        </div>
      <% end %>
    </div>
  </div>
  <%= paginate @toothbrushes, pagination_class: "flex-wrap justify-content-center", theme: 'bootstrap-5'%>
</div>

app/views/toothbrushes/index_search.html.erb
<li class="list-group-item" id="search-guide">表示された検索候補をクリックすると自動で歯ブラシ名が入力されます</li>
<% @toothbrush.each do |toothbrush| %>
  <li class="list-group-item" 
            role="option" data-autocomplete-value="<%= toothbrush.id %>" >
    <%= toothbrush.item_name %>
  </li>
<% end %>

app/views/toothbrushes/new.html.erb
<div class="container-fluid" id="search-form">
  <div class="row py-3">
    <div class="col-lg-10 offset-lg-1 text-center">
      <h1 >検索結果</h1>
    </div>
  </div>
  <% if @results.present? %>
    <div class="row">
      <% @results.each do |result| %>
        <div class="col-sm-12 col-md-6 col-lg-3 pb-2">
          <%= render "toothbrushes/search_result", result: result %>
        </div>
      <% end %>
    </div>
  <% else %>
    <p class="text-center">ごめんなさい！このキーワードを持つ歯ブラシは、楽天市場には無いみたいです・・・</p>     
    <p class="text-center">メーカー名や商品名を変えてもう一度検索してみてください。</p> 
    <%= render 'shared/search_form', url: new_toothbrush_path %>
    <%= render 'search_guide' %>
  <% end %>
  <%= render 'shared/moving_text' %>
  <%= paginate @results, pagination_class: "flex-wrap justify-content-center", theme: 'bootstrap-5', id: 'result-button'%>
</div>

<body id="animation-body">
  <%= render 'shared/loading_animation' %>
</body>

app/views/toothbrushes/search.html.erb
<div class="container" id="search-form">
  <div class='text-center'>
    <h1 class="mt-5 mb-3">使いたい歯ブラシを登録しましょう！</h1>
  </div>
  <%= render 'shared/search_form', url: new_toothbrush_path %>
  <%= render 'search_guide' %>
</div>

<%= render 'shared/loading_animation' %>

app/views/toothbrushes/show.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="text-center mt-3">
      <h4>歯ブラシの詳細</h4>
    </div>
    <div class="col-sm-12 col-lg-6 mb-3">
      <div id="toothbrushes-index">
        <div class="card">
          <div class="text-center">
            <%= image_tag @toothbrush.item_image_urls, size: '128x128' %>
          </div>
          <div class="card-body" id="card-font">
            <p class="card-title text-center">
              <%= @toothbrush.item_name %>
            </p>
            <ul class="list-group">
              <li class="list-group-item text-center">
                <%= "使っている人 : #{@toothbrush.user.name}さん" %>
                <p class="pt-2"><%= link_to "ユーザーの詳細を見る", user_path(@toothbrush.user)%></p>
              </li>
              <li class="list-group-item text-center" >
                <span>
                  使用状況 : <span id="<%= "state-#{@toothbrush.state}" %>"><%= "#{@toothbrush.state_i18n}"%></span>
                </span>
              </li>
              <li class="list-group-item text-center">
                <%= "ブラシの材質 : #{@toothbrush.brush_material_i18n}" %>
              </li>
              <li class="list-group-item text-center">
                <%= "ブラシのやわらかさ : #{@toothbrush.hardness_i18n}" %>
              </li>
              <% if @toothbrush.end_use_at %>
                <li class="list-group-item text-center">
                  <%= "使用終了日 : #{@toothbrush.end_use_at.strftime('%Y-%m-%d')}" %>
                </li>
              <% end %>
              <%  if @toothbrush.comment.present? %>
                <li class="list-group-item">
                  <p class="text-center">使ってみたコメント</p>
                  <%= @toothbrush.comment %>
                </li>
              <% end %>
              <% if @toothbrush.user == current_user %>
                <li class="list-group-item text-center">
                  <%= link_to '編集', edit_toothbrush_path(@toothbrush), 
                      class:"btn btn-dark me-2 my-2", id:"toothbrush-button" %>
                  <%= link_to 'デンタルグッズ', dental_items_search_path(@toothbrush), 
                      class:"btn btn-dark m-2", id:"toothbrush-button" %>
                  <% if @toothbrush.using? %>
                    <button type="button" class="btn end-used-button m-2" data-bs-toggle="modal" data-bs-target="#end-usedModal">
                      使い終わる
                    </button>
                    <div class="modal fade" id="end-usedModal" tabindex="-1" aria-labelledby="end-usedModalLabel" aria-hidden="true">
                      <div class="modal-dialog">
                        <div class="modal-content">
                          <div class="modal-header">
                            <h1 class="modal-title fs-5" id="end-usedModalLabel">歯ブラシを使い終わりますか？</h1>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                          </div>
                          <div class="modal-body text-start">
                            <p>現在時刻で歯ブラシの使用を終了します</p>
                            <p>以下の理由での利用がおすすめです</p>
                            <ul>
                              <li>電動歯ブラシを使い終わる場合</li>
                              <li>何らかの理由で歯ブラシを今すぐ使い終わりたい場合</li>
                            </ul>
                          </div>
                          <div class="modal-footer">
                            <button type="button" class="btn closed-button" data-bs-dismiss="modal">閉じる</button>
                            <%= link_to '決定', update_state_toothbrush_path(@toothbrush, new_state: :end_used), 
                                                method: :put, class: 'btn ms-3 end-used-button', id: 'state-end-used' %>
                          </div>
                        </div>
                      </div>
                    </div>
                  <% end %>
                  <button type="button" class="btn delete-button m-2" data-bs-toggle="modal" data-bs-target="#deleteModal">
                    削除する
                  </button>
                  <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
                    <div class="modal-dialog">
                      <div class="modal-content">
                        <div class="modal-header">
                          <h1 class="modal-title fs-5" id="deleteModalLabel">本当に歯ブラシを削除しますか？</h1>
                          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                          この操作は取り消せません
                        </div>
                        <div class="modal-footer">
                          <button type="button" class="btn closed-button" data-bs-dismiss="modal">閉じる</button>
                          <%= link_to '削除する', toothbrush_path(@toothbrush), 
                                              data: { 'turbo_method': :delete }, class: 'btn ms-3 delete-button' %>
                        </div>
                      </div>
                    </div>
                  </div>
                  <%= link_to "https://twitter.com/share?url=#{ request.url }&text=この歯ブラシ、おすすめです！%0a%0a", 
                              class: 'ms-2', target: '_blank', rel: 'noopener'  do %>
                    <i class="fa-brands fa-square-x-twitter fa-2x" style = "vertical-align: middle;"></i>
                  <% end %>
                </li>
                <% if @toothbrush.end_used? || @toothbrush.cleaning? || @toothbrush.recycling? %>
                  <li class="list-group-item d-flex justify-content-center">
                    <div>
                      <button type="button" class="btn me-2" data-bs-toggle="modal" data-bs-target="#repeatModal" id='toothbrush-button'>
                        もう一度使う!
                      </button>
                      <div class="modal fade" id="repeatModal" tabindex="-1" aria-labelledby="repeatModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                          <div class="modal-content">
                            <div class="modal-header">
                              <h1 class="modal-title fs-5" id="repeatModalLabel">同じ歯ブラシで使用を開始します</h1>
                              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                              ブラシの材質、かたさ、使用終了日については改めて設定をお願いします！
                            </div>
                            <div class="modal-footer">
                              <button type="button" class="btn closed-button" data-bs-dismiss="modal">閉じる</button>
                              <%= link_to '決定', toothbrushes_path(code: @toothbrush.item_code,
                                                                  name: @toothbrush.item_name,
                                                                  url: @toothbrush.item_url,
                                                                  image: @toothbrush.item_image_urls),
                                                                  id: 'toothbrush-button',
                                                                  data: { 'turbo_method': :post }, 
                                                                  class: 'btn ms-3' %>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                    <% if @toothbrush.end_used? || @toothbrush.cleaning? %>
                      <div>
                        <button type="button" class="btn text-center recycling-button ms-2" data-bs-toggle="modal" data-bs-target="#recyclingModal" id='state-recycling'>
                          リサイクルする！
                        </button>
                        <div class="modal fade" id="recyclingModal" tabindex="-1" aria-labelledby="recyclingModalLabel" aria-hidden="true">
                          <div class="modal-dialog">
                            <div class="modal-content">
                              <div class="modal-header">
                                <h1 class="modal-title fs-5" id="recyclingModalLabel">リサイクルしますか？</h1>
                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                              </div>
                              <div class="modal-body text-center">
                                <div>リサイクル場所は少しずつ増えています。</div>
                                <div>「歯ブラシ リサイクル」などで検索して<br />最新情報を確認しましょう！</div>
                                <div>貴方の家の近くで<br />新しくリサイクルが始まるかもしれません・・・</div>
                              </div>
                              <div class="modal-footer">
                                <button type="button" class="btn closed-button" data-bs-dismiss="modal">閉じる</button>
                                <%= link_to '決定', update_state_toothbrush_path(@toothbrush, new_state: :recycling), 
                                                    method: :put, class: 'btn ms-3 recycling-button', id: 'state-recycling' %>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                      <% if @toothbrush.end_used? %>
                        <div>
                          <button type="button" class="btn cleaning-button me-2" data-bs-toggle="modal" data-bs-target="#cleaningModal" id='state-cleaning'>
                            掃除道具として使う！
                          </button>
                          <div class="modal fade" id="cleaningModal" tabindex="-1" aria-labelledby="cleaningModalLabel" aria-hidden="true">
                            <div class="modal-dialog">
                              <div class="modal-content">
                                <div class="modal-header">
                                  <h1 class="modal-title fs-5" id="cleaningModalLabel">掃除道具として使いますか？</h1>
                                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>
                                <div class="modal-body">
                                  掃除道具としても使い終わる際は、是非リサイクルしましょう!
                                </div>
                                <div class="modal-footer">
                                  <button type="button" class="btn closed-button" data-bs-dismiss="modal">閉じる</button>
                                  <%= link_to '決定', update_state_toothbrush_path(@toothbrush, new_state: :cleaning), 
                                                      method: :put, class: 'btn ms-3 cleaning-button', id: 'state-cleaning' %>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                      <% end %>
                    <% end %>
                  </li>
                <% end %>
              <% end %>
              <% if @toothbrush.recycling? %>
                <li class="list-group-item text-center">
                  <%= link_to '歯ブラシのリサイクルについて', "https://www.lion.co.jp/ja/sustainability/toothbrush-recycling/", 
                      class: "me-2 top-link" %>
                  <%= link_to "主なリサイクル実施場所", "https://www.google.com/maps/d/u/0/viewer?mid=1vfm_m3NM73IKEE5VYVRhkV1q_La1juz0&hl=ja&ll=33.868659968878575%2C132.5573857&z=6", 
                      class: "ms-2 top-link" %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>

    <div class="col-12">
      <div class="row">
        <% if @dental_items.present? %>
          <h4 class="text-center pt-3 pb-5">
            <%= "#{@toothbrush.user.name}さんはこの歯ブラシと一緒に以下のデンタルグッズも使用されています！" %>
          </h4>
          <% @dental_items.each do |dental_item| %>
            <%= render "toothbrushes/dental_item", dental_item: dental_item %>
          <% end %>
        <% else %>
          <p class="text-center">一緒に使われているデンタルグッズはまだありません</p>
        <% end %>
      </div>
    </div>
  </div>
</div>